language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - openjdk11

before_install:
  - java -version
  - mvn --version

install:
  - mvn -s conf/settings.xml install -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -DskipTests=true -Dmaven.javadoc.skip=true -B -V
