# Valid storage methods are YAML, MONGODB and MYSQL

disableUpdater: false
shopIdentifier: '&9[SilkSpawners]'
numberFormat: '$ 00.##'
allowedActions:
- RIGHT_CLICK_BLOCK
invincibility:
  burn: true
  explode: true
  ignite: true
forceInventoryUpdate: false
perMobPermissions: false
eggMode: false
storageMethod: 'YAML'
mongoDB:
  host: 'localhost'
  port: 27017
  user: ''
  pass: ''
  database: 'silkspawners'
  collection: 'shops'
MySQL:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'shops'
