name: SilkSpawnersShopAddon
author: xGhOsTkiLLeRx
main: de.dustplanet.silkspawnersshopaddon.SilkSpawnersShopAddon
version: ${project.version}${build.number}
url: https://www.spigotmc.org/resources/12028/
description: A sign shop for SilkSpawners
commands:
  silkspawnersshopaddon:
    description: Used to edit shops, administrative command
    aliases: [silkspawnersshop, silkspawnershop, sshop, ssshop, shop]
permissions:
  silkspawners.createshop:
    description: Grants the ability to create a shop
    default: op
  silkspawners.destroyshop:
    description: Grants the ability to destroy a shop
    default: op
  silkspawners.use.*:
    children:
      silkspawners.use.buy: true
      silkspawners.use.buy.*: true
      silkspawners.use.sell: true
      silkspawners.use.sell.*: true
  silkspawners.use.buy:
    description: Allows you to use buy shops
    default: true
  silkspawners.use.sell:
    description: Allows you to use sell shops
    default: true
  silkspawners.editshop:
    description: Allows you to edit shops via the command
    default: op
depend: [SilkSpawners, Vault]
