_job_base: &job_base
  working_directory: ~/silkspawners-shop-addon
  steps:
    - checkout
    - run: java -version
    - run: mvn -version
    - restore_cache:
        key: silkspawners-shop-addon-{{ checksum "pom.xml" }}
    - run: mvn -s conf/settings.xml dependency:go-offline
    - save_cache:
        paths:
          - ~/.m2
        key: silkspawners-shop-addon-{{ checksum "pom.xml" }}
    - run: mvn -s conf/settings.xml clean package

version: 2
jobs:
  jdk8:
    <<: *job_base
    docker:
      - image: maven:3-jdk-8-slim
  jdk11:
    <<: *job_base
    docker:
      - image: maven:3-jdk-11-slim
workflows:
  version: 2
  all_jdks:
    jobs:
      - jdk8
      - jdk11
